### ISSUE TITLE
UnicodeDecodeError while pip install

### ISSUE THREAD

**Issue by omkolte17** [DAVIDhaker/django-sso#2]
line 17 in setup.py gives the error while doing a pip install:
long_description=open('README.md', 'r').read(),

Error-> UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 4181: character maps to undefined

**Comment by DAVIDhaker** [comment]
Hello! Please provide more details. Python version, system version, etc.


On my PC now all good.
![image](https://user-images.githubusercontent.com/23550085/198544479-8ba40810-1b42-417c-8629-60d13bb2bf36.png)

**Comment by omkolte17** [comment]
Python 3.10.4 (tried with 3.10.6 as well), Windows 11

![error](https://user-images.githubusercontent.com/26180402/198549657-5647c4b0-7610-40d4-8972-32aa35279d54.png)

If I change the line 17 of the setup.py and add encoding there then it is installed without any error, I think it might be due to some character encoding.
![image](https://user-images.githubusercontent.com/26180402/198550004-944a20f0-2455-4f70-b8ab-16b0645cf168.png)

**Comment by DAVIDhaker** [comment]
Sorry for long reply. I'm was unhealthy. Fix uploaded. Package updated. You can try it now!
