### ISSUE TITLE
SSO settings dict should be optional

### ISSUE THREAD

**Issue by kakulukia** [DAVIDhaker/django-sso#8]
I just installed the new version and got this error:

AttributeError: 'Settings' object has no attribute 'affected_models_fields'

I fixed it with the addition of SSO = {} to settings.py, but his should b be optional.

One additional remark: Having a settings dictionary now, it would make sense to have all other settings live in there.
Looks weird to have separate settings and an SSO dict with just one additional setting.

**Comment by DAVIDhaker** [comment]
Yes. It's not beautiful. I agree, but was in hurry with v2. In few days will push fixes.

**Comment by DAVIDhaker** [comment]
Hello! Problem fixed. Try now. Thanks for waiting. If you don't have more about this issue - please close it.

**Comment by niklaskobi** [comment]
Hello! 
I don't know if it is related, but I'm getting:
`Django SSO: SSO dictionary does not exist or not a dict`
with version 3.0.0

**Comment by DAVIDhaker** [comment]
@niklaskobi Hello. On service side SSO settings are wrong.

**Comment by DAVIDhaker** [comment]
![Screenshot_20230306_170053](https://user-images.githubusercontent.com/23550085/223131435-3009f769-660a-4707-817f-b2961a73e12b.png)

@niklaskobi, i did make more obvious error message. Now will release v3.0.1

**Comment by DAVIDhaker** [comment]
@niklaskobi, checkout update and read docs again.  
https://pypi.org/project/django-sso/3.0.1/

**Comment by niklaskobi** [comment]
Thanks! That solved the issue
