### ISSUE TITLE
This is not guaranteed to work

### ISSUE THREAD

**Issue by kakulukia** [DAVIDhaker/django-sso#9]
https://github.com/DAVIDhaker/django-sso/blob/53dd095fe94bb807b5a000c8fc9edff902375fa6/src/django_sso/sso_gateway/views.py#L219

Please change it to:  Service.objects.first()

**Comment by DAVIDhaker** [comment]
Redundant data dependency. Kidy error. Fixed... I will publish soon.

**Comment by DAVIDhaker** [comment]
Problem fixed. Try now.

**Comment by DAVIDhaker** [comment]
Checkot [it](https://github.com/DAVIDhaker/django-sso/blob/main/src/django_sso/sso_gateway/views.py#L219) and can close issue.

**Comment by kakulukia** [comment]
A static method. That looks way better! But i can only check tonight or maybe tomorrow. The sick daughter comes first. Dont know about my timing.
